In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:
x = np.array([124510, 47474, 15078, 1209, 1004]).reshape((-1, 1))
y = np.array([44421, 34674, 25771, 13554, 12777])

In [3]:
print(x)

[[124510]
 [ 47474]
 [ 15078]
 [  1209]
 [  1004]]


In [4]:
print(y)

[44421 34674 25771 13554 12777]


In [5]:
model = LinearRegression()

In [7]:
model = LinearRegression().fit(x, y)

In [8]:
r_sq = model.score(x, y)
print('coefficient of determination:', r_sq)

coefficient of determination: 0.8579160149847443


In [9]:
print('intercept:', model.intercept_)
print('slope:', model.coef_)

intercept: 17045.125810111662
slope: [0.24288137]


In [10]:
new_model = LinearRegression().fit(x, y.reshape((-1, 1)))
print('intercept:', new_model.intercept_)

intercept: [17045.12581011]


In [11]:
print('slope:', new_model.coef_)

slope: [[0.24288137]]


In [12]:
 y_pred = model.predict(x)
print('predicted response:', y_pred, sep='\n')

predicted response:
[47286.28495377 28575.67587987 20707.29107851 17338.76938416
 17288.9787037 ]


In [13]:
y_pred = model.intercept_ + model.coef_ * x
print('predicted response:', y_pred, sep='\n')

predicted response:
[[47286.28495377]
 [28575.67587987]
 [20707.29107851]
 [17338.76938416]
 [17288.9787037 ]]


In [14]:
x_new = np.arange(5).reshape((-1, 1))
print(x_new)

[[0]
 [1]
 [2]
 [3]
 [4]]


In [15]:
y_new = model.predict(x_new)
print(y_new)

[17045.12581011 17045.36869148 17045.61157285 17045.85445422
 17046.09733558]


In [8]:
est = sm.OLS(y, x)
est2 = est.fit()
print(est2.summary())

NameError: name 'sm' is not defined